/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ProducerWindow.java
 *
 * Created on 20-feb-2009, 22:10:57
 */

package com.sdds.monitor.producer;

import com.sdds.Manager;

/**
 * 
 * @author Jan-Egbert
 */
public class ProducerWindow extends javax.swing.JFrame {
	private static final long serialVersionUID = 9146052031898855029L;
	private ProducerWindowHelper helper;
	private String type;
	private String xmlSkeleton;
	private Manager manager;
	private javax.swing.JButton btnProduce;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextArea taXML;
	

	/** Creates new form ProducerWindow */
	public ProducerWindow(String type, String xmlSkeleton) {
		this.type = type;
		this.xmlSkeleton = xmlSkeleton;
		setTitle("P:" + type);
		initComponents();
		initHelper();
		initXMLSkeleton();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {
		jScrollPane1 = new javax.swing.JScrollPane();
		taXML = new javax.swing.JTextArea();
		btnProduce = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		taXML.setColumns(20);
		taXML.setRows(5);
		jScrollPane1.setViewportView(taXML);

		btnProduce.setText("Produce");
		btnProduce.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnProduceActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jScrollPane1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 398,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(btnProduce)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(31, 31, 31)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														jScrollPane1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														211,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(btnProduce))
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btnProduceActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnProduceActionPerformed
		String xml = taXML.getText().trim();
		//TODO How to produce in XML?
		helper.produce(xml, type);		
	}

	private void initHelper() {
		helper = new ProducerWindowHelper(this, manager);
	}

	private void initXMLSkeleton() {
		taXML.setText(xmlSkeleton);
	}
}
